name: Build and Lint
---
on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      
      - name: Setup Node
        uses: actions/setup-node@v5
      
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build
      
      - name: Lint
        run: npm run lint
